In [1]:
import pandas as pd

In [4]:
df = pd.read_excel('./dataset.xlsx', sheet_name='Data')

In [14]:
idx_col = df.iloc[2, :].dropna().to_numpy()[1:]
idx_col

array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0,
       13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0,
       24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0,
       35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0,
       46.0, 47.0, 48.0, 49.0, 50.0, 51.0, 52.0, 53.0, 54.0, 55.0, 56.0,
       57.0, 58.0, 59.0, 60.0, 61.0, 62.0, 63.0, 64.0], dtype=object)

In [22]:
df.iloc[3:7, 10:]

Unnamed: 10  Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  \
3          1.0          1.0          1.0          NaN          0.0   
4          1.0          0.0          1.0          NaN          1.0   
5          1.0          0.0          1.0          NaN          1.0   
6          1.0          1.0          1.0          NaN          1.0   

   Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  Unnamed: 19  ...  \
3          1.0          1.0          NaN          1.0          1.0  ...   
4          0.0          1.0          NaN          1.0          0.0  ...   
5          0.0          1.0          NaN          1.0          0.0  ...   
6          1.0          1.0          NaN          1.0          1.0  ...   

   Unnamed: 256  Unnamed: 257  Unnamed: 258  Unnamed: 259  Unnamed: 260  \
3           0.0           NaN           0.0           1.0           0.0   
4           0.0           NaN           0.0           0.0           1.0   
5           0.0           NaN           0.0           0.0           1.0   
6           0.0           NaN           0.0           1.0           0.0   

   Unnamed: 261  Unnamed: 262  Unnamed: 263  Unnamed: 264  Unnamed: 265  
3           NaN           0.0           1.0           0.0           NaN  
4           NaN           1.0           0.0           0.0           NaN  
5           NaN           1.0           0.0           0.0           NaN  
6           NaN           0.0           1.0           0.0           NaN  

[4 rows x 256 columns]

In [29]:
df.iloc[7, 10:]

Unnamed: 10     NaN
Unnamed: 11     NaN
Unnamed: 12     NaN
Unnamed: 13       0
Unnamed: 14     NaN
               ... 
Unnamed: 261      1
Unnamed: 262    NaN
Unnamed: 263    NaN
Unnamed: 264    NaN
Unnamed: 265      1
Name: 7, Length: 256, dtype: object

In [30]:
idx = 10
arrs, labels = [], []
while idx < 265:
    tmp_df = df.iloc[3:7, idx:idx+3]
    tmp_label = df.iloc[7, idx+3]
    arrs.append(tmp_df.to_numpy())
    labels.append(int(tmp_label))
    idx += 4


In [35]:
arrs

[array([[1., 1., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 1., 1.]]),
 array([[0., 1., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 1., 1.]]),
 array([[1., 1., 0.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 1., 0.]]),
 array([[1., 1., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [0., 1., 1.]]),
 array([[0., 0., 0.],
        [1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [0., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [1., 1., 0.],
        [1., 0., 1.],
        [1., 1., 1.]]),
 array([[0., 0., 0.],
        [1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 0.]]),
 array([[0., 0., 0.],
        [1., 1., 1.],
        [1., 0., 1.],
        [0., 1., 1.]]),
 array([[1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.],
        [0., 0., 0.]]),
 array([[0